site_name: Ralph Laude | Portfolio
site_url: https://ralphpaololaude.github.io/portfolio
repo_url: https://github.com/ralphpaololaude/portfolio
repo_name: ralphpaololaude/portfolio

# Theme
theme:
  name: material
  custom_dir: material/overrides
  icon:
    logo: material/code-braces
    repo: fontawesome/brands/github
  favicon: favicon.ico
  font:
    text: Noto Sans
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: custom
    accent:  custom
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: custom
    accent:  custom
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - content.tabs.link
    - navigation.tracking

# Extras
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/custom.js

# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - blog

# Footer
copyright: Copyright &copy; 2026 Ralph Laude
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ralphpaololaude
      name: ralphpaololaude on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ralphpaololaude/
      name: ralphpaololaude on LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/rappaolau
      name: ralphpaololaude on LinkedIn

# Page tree
nav:
  - Home: index.md
  - Projects:
    - projects/index.md
  - Blog:
    - blog/index.md
  - About: about.md