# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Portfolio

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Create Open API Spec static page
  generate-api-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Generate API docs
        uses: msayson/openapi-github-pages-action@v2.0.0
        with:
          api-configs: |-
            [
              {
                "openapi-json-filepath": "assets/openapi/matchaio_openapi.yaml",
                "api-doc-filepath": "docs/api-documentation/api-reference.html"
              }
            ]
          api-docs-dir: docs/api-documentation
      - name: Upload API documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs/api-documentation


  # Build job
  build:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    needs: generate-api-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3'
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Download API docs
        uses: actions/download-artifact@v4
        with:
          name: api-docs
          path: docs
      - name: Copy API docs into site
        run: cp -r docs/api-documentation _site/api-documentation
      - name: Delete old github-pages artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
