name: Generate API docs and deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-api-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    environment: github-pages  # Add this line
    steps:
      - name: Generate API docs and deploy to GitHub Pages
        uses: msayson/openapi-github-pages-action@v2.0.0
        with:
          api-configs: |-
            [
              {
                "openapi-json-filepath": "assets/openapi/matchaio_openapi.yaml",
                "api-doc-filepath": "latest/api-reference.html"
              }
            ]
          api-docs-dir: docs
